import { Transaction } from "../types/types";

export const transactionsData: Transaction[] = [
  {
    id: '0',
    title: 'Zomato',
    amount: 400,
    type: 'expense',
    category: 'Food',
    date: '2026-01-02',
    note: 'Online food order',
  },
  {
    id: '1',
    title: 'Salary',
    amount: 40000,
    type: 'income',
    category: 'Job',
    date: '2026-02-02',
    note: 'Monthly salary credited',
  },
  {
    id: '2',
    title: 'Freelance Project',
    amount: 12000,
    type: 'income',
    category: 'Freelance',
    date: '2026-02-03',
    note: 'React Native project payment',
  },
  {
    id: '3',
    title: 'Groceries',
    amount: 1800,
    type: 'expense',
    category: 'Food',
    date: '2026-02-04',
    note: 'Supermarket shopping',
  },
  {
    id: '4',
    title: 'Electricity Bill',
    amount: 2500,
    type: 'expense',
    category: 'Bills',
    date: '2026-02-07',
    note: 'Monthly electricity bill',
  },
  {
    id: '5',
    title: 'Movie Night',
    amount: 900,
    type: 'expense',
    category: 'Entertainment',
    date: '2026-02-10',
    note: 'Cinema tickets',
  },
  {
    id: '6',
    title: 'Stock Dividend',
    amount: 3000,
    type: 'income',
    category: 'Investment',
    date: '2026-02-12',
    note: 'Quarterly dividend',
  },
  {
    id: '7',
    title: 'Petrol',
    amount: 1500,
    type: 'expense',
    category: 'Transport',
    date: '2026-02-14',
    note: 'Fuel refill',
  },
  {
    id: '8',
    title: 'Youtube payment',
    amount: 1750,
    type: 'income',
    category: 'Freelance',
    date: '2026-03-01',
    note: 'Youtube channel payment payment',
  },
];
